name: solidity-unit-testing-action
on: [push]

jobs:
  run_sample_test_job:
    runs-on: ubuntu-latest
    name: A job to run sample solidity tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Environment Setup
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.6
      - name: Run SUT Action
        uses: ioedeveloper/solidity-unit-testing@v0.1.7-dev
        with:
          source-folder: 'sample/tests'
          source-file: 'sample/tests/Ballot.test.sol'